[project]
name = "canvas-to-caldav-tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "caldav==2.2.3",
    "icalendar==6.3.2",
    "pytomlpp==1.1.0",
    "requests==2.32.5",
]
